from __future__ import annotations

from functools import cache
from itertools import product
from math import gcd, isqrt, pi, prod, sqrt
from typing import TYPE_CHECKING, ClassVar

from sympy import Matrix, factorint, gcdex, primerange
from sympy.matrices.normalforms import hermite_normal_form
from sympy.solvers.diophantine.diophantine import diop_DN

from quadint.quad.int import QuadInt
from quadint.utils import _is_squarefree

if TYPE_CHECKING:
    from collections.abc import Iterator

    from quadint.quad.rings import QuadraticRing

_IDEAL_OP_TYPES = (complex, int, float, QuadInt)


def _coords(x: QuadInt) -> tuple[int, int]:
    """Return coordinates in the ring's integral basis (1, w)."""
    if x.ring.den == 1:
        return x.a, x.b

    return (x.a - x.b) // 2, x.b


def _from_coords(ring: QuadraticRing, c0: int, c1: int) -> QuadInt:
    """Create an element from coordinates in the ring's integral basis (1, w)."""
    cls = ring.DEFAULT_KLASS
    if ring.den == 1:
        return cls(c0, c1, ring, skip_basis=True)

    return cls(2 * c0 + c1, c1, ring, skip_basis=True)


def _coerce(ring: QuadraticRing, x: complex | int | float | QuadInt) -> QuadInt:
    """Coerce x into ring or raise TypeError."""
    y = ring.from_obj(x)
    if y is NotImplemented:
        raise TypeError(f"Cannot coerce {type(x).__name__} into {ring!r}")

    return y


def _canonical_hnf(a: int, b: int, c: int) -> tuple[int, int, int]:
    """Return a canonical normal form"""
    if a < 0:
        a = -a
        b = -b
    if c < 0:
        c = -c
        b = -b

    return a, b % a, c


class Ideal:
    """
    Integral ideal in a quadratic order.

    Ideals are stored as normalized rank-2 Z-lattices in the ring's integral basis.
        Iterating over a nonzero ideal yields its infinitely many elements in
            a deterministic expanding square-shell order.
    """

    __slots__ = ("ring", "hnf", "basis", "norm")

    ring: QuadraticRing
    hnf: tuple[int, int, int]
    basis: tuple[QuadInt, QuadInt]
    norm: int

    def __init__(
        self,
        ring: QuadraticRing,
        *generators: complex | int | float | QuadInt,
        _hnf: tuple[int, int, int] | None = None,
    ) -> None:
        """Create the ideal generated by elements, or from an internal HNF tuple."""
        self.ring = ring

        # TODO: Once mypyc handles __new__-based alternate constructors reliably,
        #   the _hnf path can move to a private constructor.
        if _hnf is not None:
            if generators:
                raise TypeError("cannot pass both generators and _hnf")

            a, b, c = int(_hnf[0]), int(_hnf[1]), int(_hnf[2])
            if a == 0 and b == 0 and c == 0:
                self.hnf = (0, 0, 0)
            else:
                if a == 0 or c == 0:
                    raise ValueError("Ideal HNF must be rank 2 or the zero ideal")
                self.hnf = _canonical_hnf(a, b, c)
        else:
            if not generators:
                raise TypeError("expected at least one generator or _hnf")

            vectors: list[tuple[int, int]] = []
            w = _from_coords(ring, 0, 1)
            for g in generators:
                x = _coerce(ring, g)
                vectors.extend((_coords(x), _coords(x * w)))

            matrix = Matrix([[x for x, _ in vectors], [y for _, y in vectors]])
            hnf = hermite_normal_form(matrix)

            if hnf.shape[1] == 0:
                self.hnf = (0, 0, 0)
            elif hnf.shape[1] == 2:
                a = int(hnf[0, 0])
                b = int(hnf[0, 1])
                c = int(hnf[1, 1])
                self.hnf = _canonical_hnf(a, b, c)
            else:
                raise ValueError("ideal generators must span a rank-2 lattice")

        a, b, c = self.hnf
        self.basis = (_from_coords(ring, a, 0), _from_coords(ring, b, c))
        self.norm = abs(a * c)

    def is_prime(self) -> bool:
        """Return True iff this ideal is prime."""
        if self.norm <= 1:
            return False

        factors = factorint(self.norm)
        if len(factors) != 1:
            return False

        p = next(iter(factors))
        return any(self == prime_ideal for prime_ideal in self.ring.prime_ideals_over(p))

    @cache
    def principal_generator(self) -> QuadInt | None:
        """Return a generator for this ideal if one is found, otherwise None."""
        if self.norm == 0:
            return self.ring.zero

        if self.norm == 1:
            return self.ring.one

        if self.ring.D > 0:
            return self._principal_generator_real()

        b0, b1 = self.basis
        if self.ring.supports_division() and self.ring.D < 0:
            candidate = self.ring.gcd(b0, b1)
            if Ideal(self.ring, candidate) == self:
                return candidate

        target = self.norm
        den = self.ring.den
        max_a = den * isqrt(target)
        max_b = den * isqrt(target // abs(self.ring.D) + 2)

        for a in range(-max_a, max_a + 1):
            for b in range(-max_b, max_b + 1):
                if den == 2 and ((a ^ b) & 1):
                    continue

                x = self.ring.DEFAULT_KLASS(a, b, self.ring, skip_basis=True)
                if abs(abs(x)) == target and x in self and Ideal(self.ring, x) == self:
                    return x

        return None

    def _principal_generator_real(self) -> QuadInt | None:
        """Return a real quadratic generator by solving the ideal's norm form."""
        b0, b1 = self.basis

        # Every element of this ideal is m*b0 + n*b1.
        #
        # Its norm is a binary quadratic form:
        #
        #     Q(m, n) = A*m**2 + B*m*n + C*n**2
        #
        # A principal generator exists iff Q(m, n) = ±self.norm has an
        # integer solution and the resulting element actually reconstructs
        # this ideal.
        A = abs(b0)
        C = abs(b1)
        B = abs(b0 + b1) - A - C

        delta = B * B - 4 * A * C
        if delta <= 0:
            raise ArithmeticError("Real quadratic norm form should have positive discriminant")

        sqrt_delta = isqrt(delta)
        if sqrt_delta * sqrt_delta == delta:
            raise NotImplementedError("Principal-generator search requires a nonsquare real quadratic order")

        unit_solutions = diop_DN(delta, 1)
        if not unit_solutions:
            raise ArithmeticError("Failed to find a fundamental Pell unit")

        u_, v_ = unit_solutions[0]
        u = int(u_)
        v = int(v_)
        denom = 2 * A
        modulus = abs(denom)

        fundamental_unit = self.ring.fundamental_unit()
        conjugate_unit = fundamental_unit.conjugate()

        def key(z: QuadInt) -> tuple[int, int, int, int, int]:
            return (max(abs(z.a), abs(z.b)), abs(z.a), abs(z.b), z.a, z.b)

        def reduce_unit_associate(z: QuadInt) -> QuadInt:
            """Choose a smaller generator among unit associates of z."""
            best = z

            while True:
                candidates = (
                    best,
                    -best,
                    best * fundamental_unit,
                    -(best * fundamental_unit),
                    best * conjugate_unit,
                    -(best * conjugate_unit),
                )

                new_best = min(candidates, key=key)
                if key(new_best) >= key(best):
                    return best

                best = new_best

        best_candidate: QuadInt | None = None

        for target in (self.norm, -self.norm):
            rhs = 4 * A * target

            seeds: set[tuple[int, int]] = set()
            for x0, y0 in diop_DN(delta, rhs):
                seeds.add((int(x0), int(y0)))
                seeds.add((-int(x0), int(y0)))
                seeds.add((int(x0), -int(y0)))
                seeds.add((-int(x0), -int(y0)))

            for x, y in seeds:
                seen: set[tuple[int, int]] = set()

                while True:
                    state = (x % modulus, y % modulus)
                    if state in seen:
                        break

                    seen.add(state)

                    # We introduced X = 2*A*m + B*n and Y = n.
                    # So m = (X - B*Y) / (2*A).
                    numerator = x - B * y
                    if numerator % denom == 0:
                        m = numerator // denom
                        candidate = m * b0 + y * b1

                        if (
                            abs(abs(candidate)) == self.norm
                            and candidate in self
                            and Ideal(self.ring, candidate) == self
                        ):
                            candidate = reduce_unit_associate(candidate)

                            if best_candidate is None or key(candidate) < key(best_candidate):
                                best_candidate = candidate

                    x, y = u * x + delta * v * y, v * x + u * y

        return best_candidate

    def is_principal(self) -> bool:
        """Return True iff this ideal is principal."""
        return self.principal_generator() is not None

    def conjugate(self) -> Ideal:
        """Return the conjugate ideal."""
        return Ideal(self.ring, *(x.conjugate() for x in self.basis))

    def factor(self) -> tuple[Ideal, ...]:
        """Return the prime-ideal factorization as a tuple with repeated factors."""
        if self.norm == 0:
            raise ValueError("The zero ideal does not have a prime-ideal factorization")

        if self.norm == 1:
            return ()

        out: list[Ideal] = []
        for p, exponent in factorint(self.norm).items():
            prime_ideals = self.ring.prime_ideals_over(p)

            if len(prime_ideals) == 1:
                prime_ideal = prime_ideals[0]
                prime_norm_exp = 2 if prime_ideal.norm == p * p else 1
                if exponent % prime_norm_exp:
                    raise ArithmeticError("Ideal norm is incompatible with prime-ideal factorization")
                out.extend([prime_ideal] * (exponent // prime_norm_exp))
                continue

            for prime_ideal in prime_ideals:
                power = self.ring.unit_ideal()
                multiplicity = 0
                for _ in range(exponent):
                    power *= prime_ideal
                    if power.divides(self):
                        multiplicity += 1
                    else:
                        break
                out.extend([prime_ideal] * multiplicity)

        check = prod(out, start=self.ring.unit_ideal())
        if check != self:
            raise ArithmeticError("Prime-ideal factorization did not reconstruct the ideal")

        return tuple(out)

    def divides(self, other: Ideal) -> bool:
        """Return True iff this ideal divides other."""
        if self.ring is not other.ring:
            raise TypeError("Cannot compare ideals from different rings")

        return all(x in self for x in other.basis)

    def colon(self, other: Ideal) -> Ideal:
        """Return the colon ideal (self : other)."""
        if self.ring is not other.ring:
            raise TypeError("Cannot divide ideals from different rings")

        if other.norm == 0:
            # (I : 0) is conventionally the whole ring, since x*0 is in I for all x.
            return self.ring.unit_ideal()

        if self.norm == 0:
            # (0 : J) is zero for nonzero integral ideals in a domain.
            return self.ring.zero_ideal()

        a, b, c = self.hnf
        modulus = a * c

        # This matrix stores the current candidate lattice for x.
        #
        # Initially, every ring element x = u + v*w is allowed, so the coordinate
        # lattice is just Z^2 with basis columns (1, 0), (0, 1).
        #
        # Each condition "x * y is in self" cuts this lattice down by two modular
        # linear congruences. After processing both basis elements of other, the
        # remaining lattice is exactly (self : other).
        basis_matrix = Matrix([[1, 0], [0, 1]])

        for y in other.basis:
            y0, y1 = _coords(y)

            if self.ring.den == 1:
                m00 = y0
                m01 = self.ring.D * y1
                m10 = y1
                m11 = y0
            else:
                k = (self.ring.D - 1) // 4
                m00 = y0
                m01 = k * y1
                m10 = y1
                m11 = y0 + y1

            congruences = (
                (m10, m11, c),
                (c * m00 - b * m10, c * m01 - b * m11, modulus),
            )

            for r0, r1, mod in congruences:
                if mod == 1:
                    continue

                s0 = int(r0 * basis_matrix[0, 0] + r1 * basis_matrix[1, 0])
                s1 = int(r0 * basis_matrix[0, 1] + r1 * basis_matrix[1, 1])

                if s0 == 0 and s1 == 0:
                    continue

                g = gcd(abs(s0), abs(s1))
                h = gcd(g, mod)
                q = mod // h

                s0 //= g
                s1 //= g

                u, v, d = gcdex(s0, s1)
                if int(d) != 1:
                    raise ArithmeticError("Failed to solve ideal quotient congruence")

                solution_matrix = Matrix(
                    [
                        [-s1, q * int(u)],
                        [s0, q * int(v)],
                    ],
                )

                basis_matrix = hermite_normal_form(basis_matrix * solution_matrix)

        hnf = (
            int(basis_matrix[0, 0]),
            int(basis_matrix[0, 1]),
            int(basis_matrix[1, 1]),
        )
        return Ideal(self.ring, _hnf=hnf)

    def exact_div(self, other: Ideal) -> Ideal:
        """Return the integral ideal q such that self == other * q."""
        if self.ring is not other.ring:
            raise TypeError("Cannot divide ideals from different rings")

        if other.norm == 0:
            raise ZeroDivisionError("Cannot divide by the zero ideal")

        if self.norm == 0:
            return self.ring.zero_ideal()

        if self.norm % other.norm:
            raise ValueError("Ideal division is not exact")

        if not other.divides(self):
            raise ValueError("Ideal division is not exact")

        quotient = self.colon(other)
        if other * quotient != self:
            raise ValueError("Ideal division is not exact")

        return quotient

    def __floordiv__(self, other: object) -> Ideal:
        """Return the exact integral ideal quotient."""
        if isinstance(other, Ideal):
            return self.exact_div(other)

        return NotImplemented

    def __contains__(self, x: object) -> bool:
        if not isinstance(x, _IDEAL_OP_TYPES):
            return False

        try:
            element = _coerce(self.ring, x)
        except TypeError:
            return False

        if self.norm == 0:
            return not element

        a, b, c = self.hnf
        x0, y0 = _coords(element)
        n, yr = divmod(y0, c)
        if yr:
            return False

        return (x0 - b * n) % a == 0

    def __iter__(self) -> Iterator[QuadInt]:
        """Iterate over all elements of this ideal; nonzero ideals iterate forever."""
        if self.norm == 0:
            yield self.ring.zero
            return

        b0, b1 = self.basis
        yield self.ring.zero

        radius = 1
        while True:
            for m in range(-radius, radius + 1):
                yield m * b0 - radius * b1
                yield m * b0 + radius * b1

            for n in range(-radius + 1, radius):
                yield -radius * b0 + n * b1
                yield radius * b0 + n * b1

            radius += 1

    def __mul__(self, other: object) -> Ideal:
        if isinstance(other, Ideal):
            if self.ring is not other.ring:
                raise TypeError("Cannot multiply ideals from different rings")

            return Ideal(self.ring, *(x * y for x, y in product(self.basis, other.basis)))

        if isinstance(other, _IDEAL_OP_TYPES):
            scalar = _coerce(self.ring, other)
            return Ideal(self.ring, *(scalar * x for x in self.basis))

        return NotImplemented

    def __rmul__(self, other: object) -> Ideal:
        if isinstance(other, _IDEAL_OP_TYPES):
            scalar = _coerce(self.ring, other)
            return Ideal(self.ring, *(scalar * x for x in self.basis))

        return NotImplemented

    def __pow__(self, exp: int) -> Ideal:
        if exp < 0:
            raise ValueError("Negative ideal powers require fractional ideals")

        result = self.ring.unit_ideal()
        base = self
        e = int(exp)
        while e:
            if e & 1:
                result *= base

            e >>= 1
            if e:
                base *= base

        return result

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Ideal):
            return False

        return self.ring == other.ring and self.hnf == other.hnf

    def __hash__(self) -> int:
        return hash((self.ring, self.hnf))

    def __repr__(self) -> str:
        if self.norm == 0:
            return f"Ideal({self.ring!r}, 0)"

        return f"Ideal({self.ring!r}, {self.basis[0]!r}, {self.basis[1]!r})"

    def __str__(self) -> str:
        if self.norm == 0:
            return "(0)"

        return f"({self.basis[0]}, {self.basis[1]})"


class IdealClass:
    """Ideal class represented by a nonzero integral ideal."""

    __slots__ = ("representative", "_order")

    representative: Ideal
    _order: int | None

    def __init__(self, representative: Ideal) -> None:
        """Create the ideal class represented by a nonzero integral ideal."""
        if representative.norm == 0:
            raise ValueError("The zero ideal does not define an ideal class")

        self.representative = representative
        self._order = None

    @property
    def ring(self) -> QuadraticRing:
        """Return the underlying quadratic ring."""
        return self.representative.ring

    @property
    def order(self) -> int:
        """Return the multiplicative order of this ideal class."""
        if self._order is not None:
            return self._order

        power = self.representative
        order = 1
        while not power.is_principal():
            power *= self.representative
            order += 1

        self._order = order
        return order

    def is_trivial(self) -> bool:
        """Return True iff this is the principal ideal class."""
        return self.representative.is_principal()

    def inverse(self) -> IdealClass:
        """Return the inverse ideal class."""
        return IdealClass(self.representative.conjugate())

    def __mul__(self, other: object) -> IdealClass:
        if not isinstance(other, IdealClass):
            return NotImplemented

        if self.ring is not other.ring:
            raise TypeError("Cannot multiply ideal classes from different rings")

        return IdealClass(self.representative * other.representative)

    def __pow__(self, exp: int) -> IdealClass:
        e = int(exp)
        if e == 0:
            return IdealClass(self.ring.unit_ideal())

        if e < 0:
            return self.inverse() ** -e

        return IdealClass(self.representative**e)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, IdealClass):
            return False

        if self.ring is not other.ring:
            return False

        return (self.representative * other.representative.conjugate()).is_principal()

    def __hash__(self) -> int:
        return hash(self.representative.ring)

    def __repr__(self) -> str:
        return f"IdealClass({self.representative!r})"

    def __str__(self) -> str:
        return f"[{self.representative}]"


# @cache
# This is a trick I learned recently to make a singleton class and would work here, and does in pure python
# But boy does mypyc hate it, it completely crashes everything...
# we'll have to make singleton classes the old-fashioned way...
class ClassGroup:
    """Ideal class group of a quadratic order."""

    __slots__ = ("ring", "_classes", "_generators", "_initialized")

    _CACHE: ClassVar[dict[tuple[type, int, int], ClassGroup]] = {}

    ring: QuadraticRing
    _classes: tuple[IdealClass, ...] | None
    _generators: tuple[IdealClass, ...] | None
    _initialized: bool

    def __new__(cls, ring: QuadraticRing):
        """Return the cached class group for this exact kind of quadratic ring."""
        if ring.D in (0, 1) or (ring.D != -1 and not _is_squarefree(ring.D)):
            raise NotImplementedError("Class groups require a quadratic field/order")

        key = (type(ring), ring.D, ring.den)
        inst = cls._CACHE.get(key)
        if inst is not None:
            return inst

        inst = super().__new__(cls)
        cls._CACHE[key] = inst
        return inst

    def __init__(self, ring: QuadraticRing) -> None:
        """Create the ideal class group of ring."""
        if getattr(self, "_initialized", False):
            return

        self.ring = ring
        self._classes = None
        self._generators = None
        self._initialized = True

    @property
    def minkowski_bound(self) -> int:
        """Return a norm bound for ideal-class representatives."""
        disc = self.ring.discriminant()
        if disc < 0:
            return int(2 * sqrt(abs(disc)) / pi) + 1

        return int(sqrt(disc) / 2) + 1

    @property
    def generators(self) -> tuple[IdealClass, ...]:
        """Return prime ideal classes that generate this class group."""
        if self._generators is not None:
            return self._generators

        out: list[IdealClass] = []

        for p in primerange(2, self.minkowski_bound + 1):
            for ideal in self.ring.prime_ideals_over(p):
                if ideal.norm > self.minkowski_bound:
                    continue

                cls = IdealClass(ideal)
                if not cls.is_trivial() and not self._contains_class(out, cls):
                    out.append(cls)

        self._generators = tuple(out)
        return self._generators

    @property
    def classes(self) -> tuple[IdealClass, ...]:
        """Return all ideal classes in this class group."""
        if self._classes is not None:
            return self._classes

        out = [IdealClass(self.ring.unit_ideal())]

        for generator in self.generators:
            self._adjoin(out, generator)

        self._classes = tuple(out)
        return self._classes

    @property
    def order(self) -> int:
        """Return the class number of the underlying quadratic order."""
        return len(self.classes)

    def class_number(self) -> int:
        """Return the class number of the underlying quadratic order."""
        return self.order

    def __len__(self) -> int:
        return self.order

    def __iter__(self) -> Iterator[IdealClass]:
        return iter(self.classes)

    def __contains__(self, cls: object) -> bool:
        if not isinstance(cls, IdealClass):
            return False

        if cls.ring is not self.ring:
            return False

        return self._contains_class(self.classes, cls)

    def __repr__(self) -> str:
        return f"ClassGroup({self.ring!r})"

    def __hash__(self):
        return hash(self.ring)

    def _contains_class(self, classes: list[IdealClass] | tuple[IdealClass, ...], cls: IdealClass) -> bool:
        """Return True iff classes already contains cls."""
        return any(cls == known for known in classes)

    def _adjoin(self, classes: list[IdealClass], generator: IdealClass) -> None:
        """Expand classes in-place until it is closed under multiplication by generator."""
        todo = [generator]

        while todo:
            cls = todo.pop()
            if self._contains_class(classes, cls):
                continue

            classes.append(cls)

            for known in classes:
                product = cls * known
                if not self._contains_class(classes, product) and not self._contains_class(todo, product):
                    todo.append(product)
